### PR TITLE
added option for selfhosted fonts

### PR DESCRIPTION
**Pull request by deployn**
Unfortunately, it is not clarified whether offering Google Fonts via their CDN is in compliance with the GDPR. I have therefore changed the plugin from gatsby-plugin-google-fonts to [gatsby-plugin-google-webfonts](https://github.com/hupe1980/gatsby-plugin-webfonts). In the siteConfig is an option whether you want to store the fonts locally or not.

### CODE REVIEW

**Review by anarion80 — COMMENTED** [review]
Thanks! I will take it, but looks like you (your editor) are adding all those extra semicolons, which my eslint is complaining about...

Can you remove them? Or can I always just change the plugin and commit myself.

**Comment by deployn** [comment]
Thanks for the reply, I will try to remove them. But of course you can also just switch the plugin.

**Comment by deployn** [comment]
Removed them :)

**Comment by anarion80** [comment]
Thanks!

**Pull request merged**
